services:
  db:
    image: postgres:15
    container_name: people_counter_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=people_counter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  api:
    container_name: people_counter_api
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  dashboard:
    container_name: people_counter_dashboard
    build: .
    command: streamlit run dashboard.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api

volumes:
  postgres_data: